baseURL = "https://isbsh.rip"
languageCode = "ja-jp"
defaultContentLanguage = "ja"
title = "isbsh"
theme = "anubis2"

[pagination]
pagerSize = 5

[params.author]
name = "isbsh"

[params]
description = "isbsh log"
dateFormat = "2006-01-02"
paginationSinglePost = true

readNextPosts = 2

rssAsSocialIcon = true
locale = "ja-jp"
toc = true

[params.anubis2]
    enableMathGlobally = true # MathJax (default is false)
    enableCopyCodeButton = true
    enableReadMoreButton = true
    hideFooterAttribution = false # hide "Powered by Hugo, theme" in footer
    colorTheme = "auto"
    enableColorThemeSwitcher = true

    social = [
        { id = "mastodon", url = "https://nightly.fedibird.com/@isbsh", html_attributes = "rel=\"me\"" },
        { id = "bluesky", url = "https://isbsh.bsky.social" },
    ]

    customCSS = [
        "custom-css/custom1.scss", 
        "custom-css/custom2.css",
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    ]

    customJS = [
        "https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"
    ]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 3

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 4

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
anchorLineNos      = false
codeFences         = true # tested with true and false. Both work.
noClasses          = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
style              = 'catppuccin-frappe' # Find more style at here: https://swapoff.org/chroma/playground/
tabWidth           = 4

[permalinks]
  posts = "/posts/:year/:slug/"